# Generated by Django 5.2.1 on 2025-05-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='iso2_code',
        ),
        migrations.AddField(
            model_name='users',
            name='flag_emoji',
            field=models.CharField(default='🌐', max_length=2),
        ),
    ]
