# Generated by Django 5.2.1 on 2025-06-27 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Usernames can be at most 12 characters.', 'unique': 'A user with that username already exists.'}, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='', regex='^[\\w.@+-]+$')]),
        ),
    ]
