# Generated by Django 5.2.1 on 2025-05-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0003_alter_users_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='top_cps_game_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.games'),
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
