# Generated by Django 5.2.1 on 2025-05-28 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('player_one_cps', models.FloatField(default=0)),
                ('player_two_cps', models.FloatField(default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(blank=True, max_length=150, null=True)),
                ('active', models.BooleanField(default=False)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_player_one', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_as_player_two', to=settings.AUTH_USER_MODEL)),
                ('winning_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_as_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
