# Generated by Django 5.2.1 on 2025-06-13 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('player_one_cps', models.FloatField(default=0)),
                ('player_one_clicks', models.FloatField(default=0)),
                ('player_two_cps', models.FloatField(default=0, null=True)),
                ('player_two_clicks', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(blank=True, max_length=150, null=True)),
                ('started', models.BooleanField(default=False)),
            ],
        ),
    ]
