# Generated by Django 5.2.1 on 2025-05-28 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='id',
        ),
        migrations.AlterField(
            model_name='games',
            name='game_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
