# Generated by Django 5.2.1 on 2025-06-13 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='games',
            name='player_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_as_player_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='games',
            name='winning_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_as_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
