# Generated by Django 5.2.1 on 2025-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
