# Generated by Django 5.2.1 on 2025-06-10 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_games_id_alter_games_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeGameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_current_cps', models.FloatField(default=0)),
                ('player_two_current_cps', models.FloatField(default=0, null=True)),
                ('started', models.BooleanField(default=False)),
                ('game_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.games')),
            ],
        ),
    ]
