# Generated by Django 5.2.1 on 2025-06-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_realtimegamedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='player_one_clicks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='player_two_clicks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RealTimeGameData',
        ),
    ]
