# Generated by Django 5.2.1 on 2025-07-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='player_one_clicks',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='player_one_cps',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='player_two_clicks',
            field=models.FloatField(default=0, null=True),
        ),
    ]
