# .github/workflows/azure-webapp.yml
name: Build & deploy Django (CPSBattles) to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write            # needed for azure/login OIDC

env:
  AZURE_WEBAPP_NAME: CPSBattles
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1 ‒ checkout -----------------------------------------------------------
    - uses: actions/checkout@v4

    # 2 ‒ (optional) local smoke-test of your code ---------------------------
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install deps & (optionally) run tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # python manage.py test          # <-- if you have tests
        python manage.py collectstatic --noinput || true

    # 3 ‒ archive the source (zip-deploy works better than shipping a folder)
    - name: Make deployment ZIP
      run: |
        zip -r ${{ github.workspace }}/deploy.zip . -x '*.git*' '**/__pycache__/**'

    # 4 ‒ login with OIDC (no secret JSON needed)
    - uses: azure/login@v2
      with:
        client-id:      ${{ secrets.AZUREAPPSER
